In [1]:
import numpy as np
from math import factorial

# For grid World

In [97]:
def calculate(state, action):
    #From A to A'
    if state == (0, 1): 
        next_state = (4,1)
        r = 10
        return next_state,r
    #From B to B'
    if state == (0, 3): 
        next_state = (2,3)
        r = 5
        return next_state,r
    #Normal movements with 0 reward
    next_state = (state[0] + action[0], state[1] + action[1])
    if ((next_state[0] >= 0 and next_state[0] < 5) and
        (next_state[1] >= 0 and next_state[1] < 5)):
        r=0
        return next_state, r
    #If Wall
    r = -1
    return state, -1 

# Q2

In [5]:
actions = [(0, -1), (0, 1), (1, 0), (-1, 0)]
epochs = 90
gamma = 0.9    #given in grid world example
#since there are 4 actions possible, and each action is equi probable
prob = 0.25
v_pi = np.zeros((5, 5))
while epochs>0:
    v_n = np.zeros((5, 5))
    #i and j represents all the states
    for i in range(5):
        for j in range(5):
            #For each action
            for a in actions:
                state, reward = calculate((i, j), a)
                v_n[i, j] = v_n[i, j] + prob * (reward + gamma * v_pi[state[0], state[1]])
    v_pi = v_n
    if epochs % 20 == 0: 
        print(v_pi, '\n-------')
    epochs = epochs - 1

[[-0.5 10.0 -0.2 5.0 -0.5]
 [-0.2 0.0 0.0 0.0 -0.2]
 [-0.2 0.0 0.0 0.0 -0.2]
 [-0.2 0.0 0.0 0.0 -0.2]
 [-0.5 -0.2 -0.2 -0.2 -0.5]] 
-------
[[3.3 8.8 4.4 5.3 1.5]
 [1.5 3.0 2.3 1.9 0.5]
 [0.1 0.8 0.7 0.4 -0.4]
 [-1.0 -0.4 -0.3 -0.6 -1.2]
 [-1.8 -1.3 -1.2 -1.4 -1.9]] 
-------
[[3.3 8.8 4.4 5.3 1.5]
 [1.5 3.0 2.3 1.9 0.6]
 [0.1 0.7 0.7 0.4 -0.4]
 [-1.0 -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2.0]] 
-------
[[3.3 8.8 4.4 5.3 1.5]
 [1.5 3.0 2.3 1.9 0.5]
 [0.1 0.7 0.7 0.4 -0.4]
 [-1.0 -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2.0]] 
-------
[[3.3 8.8 4.4 5.3 1.5]
 [1.5 3.0 2.3 1.9 0.5]
 [0.1 0.7 0.7 0.4 -0.4]
 [-1.0 -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2.0]] 
-------
[[3.3 8.8 4.4 5.3 1.5]
 [1.5 3.0 2.3 1.9 0.5]
 [0.1 0.7 0.7 0.4 -0.4]
 [-1.0 -0.4 -0.4 -0.6 -1.2]
 [-1.9 -1.3 -1.2 -1.4 -2.0]] 
-------


# Q4

In [8]:
epochs = 90
v_pi = np.zeros((5, 5))
while epochs>0:
    #For each state
    for i in range(5):
        for j in range(5):
            v = []
            #For each action
            for a in actions:
                state, reward = calculate((i, j), a)
                v.append(reward + gamma * v_pi[state[0], state[1]])
            #Select the optimal value
            v_pi[i, j] = np.max(v)
    if epochs % 20 == 0: 
        print(v_pi, '\n-------')
        print(v, '\n-------')
    epochs = epochs - 1

[[21.9 24.3 21.9 19.3 17.4]
 [19.7 21.9 19.7 17.7 16.0]
 [17.7 19.7 17.7 16.0 14.4]
 [15.9 17.7 16.0 14.4 12.9]
 [14.3 16.0 14.4 12.9 11.6]] 
-------
[11.644192367880379, 9.457587818747719, 9.457587818747719, 11.644192367880379] 
-------
[[22.0 24.4 22.0 19.4 17.5]
 [19.8 22.0 19.8 17.8 16.0]
 [17.8 19.8 17.8 16.0 14.4]
 [16.0 17.8 16.0 14.4 13.0]
 [14.4 16.0 14.4 13.0 11.7]] 
-------
[11.67973581445638, 9.511761643737811, 9.511761643737811, 11.67973581445638] 
-------
[[22.0 24.4 22.0 19.4 17.5]
 [19.8 22.0 19.8 17.8 16.0]
 [17.8 19.8 17.8 16.0 14.4]
 [16.0 17.8 16.0 14.4 13.0]
 [14.4 16.0 14.4 13.0 11.7]] 
-------
[11.679736758540042, 9.511763082670386, 9.511763082670386, 11.679736758540042] 
-------
[[22.0 24.4 22.0 19.4 17.5]
 [19.8 22.0 19.8 17.8 16.0]
 [17.8 19.8 17.8 16.0 14.4]
 [16.0 17.8 16.0 14.4 13.0]
 [14.4 16.0 14.4 13.0 11.7]] 
-------
[11.679736758565118, 9.511763082708606, 9.511763082708606, 11.679736758565118] 
-------


# EX : 4.1

In [9]:
class grid_world():
    def __init__(self,gamma=1,theta=0.01,policy=0.25):
        self.gamma = gamma
        self.theta = theta
        self.policy = policy
        self.actions = [(0, -1), (0, 1), (1, 0), (-1, 0)]
        self.value = np.zeros((4, 4))
        
    def evaluate(self, state, action):
        next_state = [state[0] + action[0], state[1] + action[1]]
        if ((next_state[0] >= 0 and next_state[0] < 4) and (next_state[1] >= 0 and next_state[1] < 4)):
            return next_state, -1
        #Wall : cant take any action
        return state, -1 
    
    def start_execution(self):
        itr = 1
        while True:
            #Policy Evaluation
            while True:
                delta = 0 
                for i in range(4):
                    for j in range(4):
                        if (i,j) == (0,0) or (i,j) == (3,3):
                            continue
                        v_prev = self.value[i, j]
                        tmp = 0
                        for a in self.actions:
                            next_state, reward = self.evaluate([i,j], a)
                            tmp = tmp + (self.policy * (reward + self.gamma * self.value[next_state[0], next_state[1]]))
                        self.value[i, j] = tmp
                        delta = max(delta, abs(self.value[i, j]-v_prev))
                if delta < self.theta:
                    break
            #Policy Improvement
            policy_stable = True
            policy_changes = 0
            for i in range(0,4):
                for j in range(0,4):
                    action_returns = []
                    old_action = self.policy
                    for a in self.actions:
                        if (0 <= a[0] <= i) or (j >= abs(a[1]) > 0):
                            s,r = self.evaluate([i, j], a)
                            action_returns.append(r)
                        else:
                            action_returns.append(0)
                    self.policy = self.actions[np.argmax(action_returns)]
                    if old_action != self.policy:
                        policy_stable = False
                        policy_changes = policy_changes+1
            #print('iteration ',itr)
            #print('policies changed= ',policy_changes)
            if policy_stable:
                break
            itr = itr + 1
        #print('Updated Value')
        print(self.value)
        #print('Updated Policy')
        #print(self.policy)
        
g = grid_world()
g.start_execution()

[[0.0 -14.0 -20.0 -22.0]
 [-14.0 -18.0 -20.0 -20.0]
 [-20.0 -20.0 -18.0 -14.0]
 [-22.0 -20.0 -14.0 0.0]]


# EX : 4.7

In [58]:
class car_rental():
    def __init__(self, gamma=0.9, theta=1e-4):
        self.gamma = gamma
        self.theta = theta
        self.action = np.arange(-5, 6)
        self.policy = np.zeros((21, 21), dtype=int)
        self.value = np.zeros((21, 21))
        self.prob = []
        for i in range(0,8):
            for j in range(0,10):
                for k in range(0,8):
                    for l in range(0,6):
                        self.prob.append(self.poisson(i, 3)*self.poisson(j, 4)*self.poisson(k, 3)*self.poisson(l, 2))
        self.states = [(i, j) for i in range(21) for j in range(21)]
    def poisson(self, n, l):
        return np.exp(-l) * pow(l, n) / factorial(n)

    def evaluate(self,state, r, v):
        # shuttle one car
        if r > 0: 
            returns = 2 
        returns = (-2) * abs(r)
        state = (min(state[0] - r, 20), min(state[1] + r, 20))
        reward = []
        for i in range(0,8):
            for j in range(0,10):
                for k in range(0,8):
                    for l in range(0,6):
                        if (min(state[0] - min(state[0], i) + k, 20) > 10 or min(state[1] - min(state[1], j) + l, 20) > 10):
                            reward.append((min(state[0], i) + min(state[1], j))*10 + 4)
                        else:
                            #Penalty for more than 10 cars
                            reward.append((min(state[0], i) + min(state[1], j))*10)
        reward = np.array(reward)
        new_state = []
        for i in range(0,8):
            for j in range(0,10):
                for k in range(0,8):
                    for l in range(0,6):
                        new_state.append((min(state[0] - min(state[0], i) + k, 20), min(state[1] - min(state[1], j) + l, 20)))
        new_state = np.array(new_state)
        returns = returns + np.sum(self.prob * (reward + self.gamma * v[new_state[:,0], new_state[:,1]]))
        return returns

    def start_execution(self):
        itr = 0
        while 1:
            #Policy evaluation
            while 1:
                delta = 0
                for state in self.states:
                    v_prev = self.value[state[0], state[1]]
                    self.value[state[0], state[1]] = self.evaluate([state[0], state[1]], self.policy[state[0], state[1]], self.value)
                    delta = max(delta, abs(self.value[state[0], state[1]]-v_prev))
                if delta < self.theta:
                    break
            #Policy Improvement
            policy_stable = True
            policy_changes = 0
            for state in self.states:
                action_returns = []
                old_action = self.policy[state[0], state[1]]
                for a in self.action:
                    if (0 <= a <= state[0]) or (state[1] >= abs(a) > 0):
                        action_returns.append(self.evaluate([state[0], state[1]], a, self.value))
                    else:
                        action_returns.append(-np.Infinity)
                self.policy[state[0], state[1]] = self.action[np.argmax(action_returns)]
                if old_action != self.policy[state[0], state[1]]:
                    policy_stable = False
                    policy_changes = policy_changes+1
            print('iteration ',itr)
            print('policies changed= ',policy_changes)
            if policy_stable:
                break
            itr = itr + 1
        print('Updated Value')
        print(self.value)
        print('Updated Policy')
        print(self.policy)

In [59]:
c = car_rental()
c.start_execution()

iteration  0
policies changed=  285
iteration  1
policies changed=  226
iteration  2
policies changed=  38
iteration  3
policies changed=  2
iteration  4
policies changed=  0
Updated Value
[[257.32008371 266.80760209 276.14474633 285.16100729 293.70485113
  301.69899453 309.14420386 316.50958833 323.45815306 330.30972033
  336.84061491 343.08072206 349.14973396 355.14606527 361.07852781
  366.94593478 372.71761995 378.26365072 383.51111251 388.42851957
  393.03582042]
 [266.69395948 276.18139568 285.51813814 294.53339024 303.07548248
  311.06722322 318.50958984 325.45815456 332.30972181 338.84061638
  345.08072352 351.1497354  357.14606671 363.07852924 368.94593595
  374.71762111 380.26365189 385.51111367 390.42852074 395.03582121
  399.54134222]
 [275.5969947  285.08405483 294.41896348 303.42962457 311.96378538
  319.94474534 327.37455673 334.30972393 340.84061848 347.0807256
  353.14973748 359.14606878 365.0785313  370.9459378  376.71762296
  382.26365373 387.51111552 392.4285226  39